// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWE8He-iAqbUjeypFwU8e8uN4Zt9Ubjbc',
    appId: '1:151526909791:web:f53fb80790bc45b21178ea',
    messagingSenderId: '151526909791',
    projectId: 'cameo-a7762',
    authDomain: 'cameo-a7762.firebaseapp.com',
    storageBucket: 'cameo-a7762.appspot.com',
    measurementId: 'G-DJSFGHD81C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6CjcfYkDf1tYFXP-P1Hw6RIbl5BRIJyo',
    appId: '1:151526909791:android:e31baf706cb8d2d71178ea',
    messagingSenderId: '151526909791',
    projectId: 'cameo-a7762',
    storageBucket: 'cameo-a7762.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnXRjr1J7UXScRIwGLyzlYOJYAB3WgKPk',
    appId: '1:151526909791:ios:c730575bd853b3751178ea',
    messagingSenderId: '151526909791',
    projectId: 'cameo-a7762',
    storageBucket: 'cameo-a7762.appspot.com',
    iosBundleId: 'com.example.tigorStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnXRjr1J7UXScRIwGLyzlYOJYAB3WgKPk',
    appId: '1:151526909791:ios:16558b2a4308781a1178ea',
    messagingSenderId: '151526909791',
    projectId: 'cameo-a7762',
    storageBucket: 'cameo-a7762.appspot.com',
    iosBundleId: 'com.example.tigorStore.RunnerTests',
  );
}
